import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function seed() {
  const FORM_ID = 'course-application-form-v1';
  
  // Delete existing if present
  await prisma.form.deleteMany({ where: { id: FORM_ID } });

  // Rich styling that matches the reference image
  const globalStyles = JSON.stringify({
    'bg': '#ffffff',
    'radius': '16px',
    'padding': '44px 48px',
    'border': '#e8eaf0',
    'border-width': '1px',
    'shadow': '0 4px 40px rgba(0,0,0,0.08)',
    'max-width': '560px',
    'font-body': "Inter, 'DM Sans', -apple-system, sans-serif",
    'font-heading': "Inter, 'DM Sans', -apple-system, sans-serif",
    'input-bg': '#ffffff',
    'input-border': '#d1d5db',
    'input-radius': '6px',
    'input-padding': '10px 14px',
    'input-font-size': '14px',
    'input-text': '#111827',
    'input-placeholder': '#9ca3af',
    'input-focus-border': '#1e3a8a',
    'input-focus-ring': 'rgba(30,58,138,0.15)',
    'input-hover-border': '#9ca3af',
    'input-error-border': '#dc2626',
    'input-error-bg': '#fef2f2',
    'input-disabled-bg': '#f9fafb',
    'focus-ring-width': '3px',
    'label-color': '#374151',
    'label-size': '13.5px',
    'label-weight': '500',
    'label-gap': '6px',
    'label-transform': 'none',
    'help-color': '#9ca3af',
    'help-size': '12px',
    'error-color': '#dc2626',
    'error-size': '12px',
    'error-weight': '500',
    'text': '#111827',
    'text-secondary': '#6b7280',
    'required-color': '#dc2626',
    'row-gap': '18px',
    'col-gap': '14px',
    'choice-row-gap': '8px',
    'choice-gap': '10px',
    'choice-size': '17px',
    'choice-border': '#d1d5db',
    'choice-bg': '#ffffff',
    'choice-checked-bg': '#1e3a8a',
    'choice-checked-border': '#1e3a8a',
    'choice-checkmark': '#ffffff',
    'btn-bg': '#1e3a8a',
    'btn-text': '#ffffff',
    'btn-radius': '6px',
    'btn-padding': '13px 48px',
    'btn-font-size': '15px',
    'btn-weight': '600',
    'btn-shadow': '0 4px 14px rgba(30,58,138,0.30)',
    'btn-hover-bg': '#1e40af',
    'btn-hover-text': '#ffffff',
    'btn-hover-shadow': '0 6px 20px rgba(30,58,138,0.40)',
    'btn-hover-lift': '-2px',
    'btn-width': 'auto',
    'select-panel-bg': '#ffffff',
    'select-panel-border': '#e5e7eb',
    'select-panel-radius': '8px',
    'select-panel-shadow': '0 8px 24px rgba(0,0,0,0.10)',
    'select-option-hover-bg': '#f3f4f6',
    'select-option-selected-bg': '#eff6ff',
    'select-option-selected-text': '#1e3a8a',
    'success-bg': '#f0fdf4',
    'success-border': '#bbf7d0',
    'success-text': '#166534',
    'success-radius': '8px',
    'title-color': '#111827',
    'title-size': '26px',
    'title-weight': '700',
    'title-align': 'center',
    'subtitle-color': '#6b7280',
    'subtitle-size': '14px',
    'transition-duration': '0.18s',
    'align': 'center',
    'margin': '0 auto',
  });

  const form = await prisma.form.create({
    data: {
      id: FORM_ID,
      shop: 'knr-technical-test.myshopify.com',
      title: 'Course Application',
      status: 'ACTIVE',
      globalStyles,
      fields: {
        create: [
          {
            id: `${FORM_ID}-firstname`,
            type: 'text',
            label: 'First name',
            order: 1,
            settings: JSON.stringify({ required: true, placeholder: 'First' }),
            styles: JSON.stringify({ width: 50 }),
          },
          {
            id: `${FORM_ID}-lastname`,
            type: 'text',
            label: 'Last name',
            order: 2,
            settings: JSON.stringify({ required: true, placeholder: 'Last' }),
            styles: JSON.stringify({ width: 50 }),
          },
          {
            id: `${FORM_ID}-course`,
            type: 'radio',
            label: 'Which course are you applying for?',
            order: 3,
            settings: JSON.stringify({
              required: true,
              options: [
                { label: 'Course A', value: 'course-a' },
                { label: 'Course B', value: 'course-b' },
                { label: 'Course C', value: 'course-c' },
              ],
              inline: true,
            }),
            styles: JSON.stringify({ displayMode: 'default' }),
          },
          {
            id: `${FORM_ID}-dob`,
            type: 'date',
            label: 'Date of birth',
            order: 4,
            settings: JSON.stringify({ required: true, placeholder: 'dd/MMM/yyyy' }),
          },
          {
            id: `${FORM_ID}-gender`,
            type: 'radio',
            label: 'Gender',
            order: 5,
            settings: JSON.stringify({
              required: true,
              options: [
                { label: 'Male', value: 'male' },
                { label: 'Female', value: 'female' },
              ],
              inline: true,
            }),
            styles: JSON.stringify({ displayMode: 'default' }),
          },
          {
            id: `${FORM_ID}-education`,
            type: 'dropdown',
            label: 'Education',
            order: 6,
            settings: JSON.stringify({
              required: true,
              placeholder: 'Select your education level',
              options: [
                { label: 'High School', value: 'highschool' },
                { label: "Bachelor's Degree", value: 'bachelors' },
                { label: "Master's Degree", value: 'masters' },
                { label: 'PhD', value: 'phd' },
                { label: 'Other', value: 'other' },
              ],
            }),
          },
          {
            id: `${FORM_ID}-email`,
            type: 'email',
            label: 'Email',
            order: 7,
            settings: JSON.stringify({ required: true, placeholder: 'you@example.com' }),
          },
          {
            id: `${FORM_ID}-phone`,
            type: 'phone',
            label: 'Contact number',
            order: 8,
            settings: JSON.stringify({ required: true, placeholder: '+1 (555) 000-0000' }),
          },
          {
            id: `${FORM_ID}-street`,
            type: 'text',
            label: 'Street Address',
            order: 9,
            settings: JSON.stringify({ placeholder: 'Street Address' }),
          },
          {
            id: `${FORM_ID}-address2`,
            type: 'text',
            label: 'Address Line 2',
            order: 10,
            settings: JSON.stringify({ placeholder: 'Address Line 2' }),
          },
          {
            id: `${FORM_ID}-city`,
            type: 'text',
            label: 'City',
            order: 11,
            settings: JSON.stringify({ required: false, placeholder: 'City' }),
            styles: JSON.stringify({ width: 50 }),
          },
          {
            id: `${FORM_ID}-state`,
            type: 'text',
            label: 'State/Region/Province',
            order: 12,
            settings: JSON.stringify({ placeholder: 'State/Region/Province' }),
            styles: JSON.stringify({ width: 50 }),
          },
          {
            id: `${FORM_ID}-zip`,
            type: 'text',
            label: 'Postal / Zip Code',
            order: 13,
            settings: JSON.stringify({ placeholder: 'Postal / Zip Code' }),
            styles: JSON.stringify({ width: 50 }),
          },
          {
            id: `${FORM_ID}-country`,
            type: 'dropdown',
            label: 'Country',
            order: 14,
            settings: JSON.stringify({
              placeholder: 'Country',
              options: [
                { label: 'United States', value: 'us' },
                { label: 'United Kingdom', value: 'uk' },
                { label: 'Canada', value: 'ca' },
                { label: 'Australia', value: 'au' },
                { label: 'Pakistan', value: 'pk' },
                { label: 'India', value: 'in' },
                { label: 'Germany', value: 'de' },
                { label: 'France', value: 'fr' },
                { label: 'Other', value: 'other' },
              ],
            }),
            styles: JSON.stringify({ width: 50 }),
          },
        ]
      }
    }
  });

  console.log('✅ Course Application form created with ID:', FORM_ID);
  console.log('   Fields:', 14);
}

seed().catch(console.error).finally(() => prisma.$disconnect());
